version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=hpxh
      - DB_USER=root
      - DB_PASSWORD=jujingyi
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: hpxh
      MYSQL_USER: user
      MYSQL_PASSWORD: jujingyi
      MYSQL_ROOT_PASSWORD: jujingyi
    ports:
      - "3306:3306"